### ISSUE TITLE
Component can't start up at Home Assistant 

### ISSUE THREAD

**Issue by MESlammer** [jethome-ru/hassio-component-smart-thermostat#1]
After installation and configuration, component does not show up in HA. There are these errors in home-assistant.log:
```
2021-12-19 04:14:36 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform smart_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/smart_thermostat/climate.py", line 448, in async_added_to_hass
    attrs = old_state.attributes.get(controller.get_unique_id(), {})
AttributeError: 'NoneType' object has no attribute 'attributes'
```
Adding smart_thermostat into configuration.yaml causes these errors:
```
2021-12-19 04:14:36 ERROR (MainThread) [homeassistant.components.climate] Error while setting up smart_thermostat platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/smart_thermostat/climate.py", line 448, in async_added_to_hass
    attrs = old_state.attributes.get(controller.get_unique_id(), {})
AttributeError: 'NoneType' object has no attribute 'attributes'
```
I use Home Assistant 2021.12.3, installed as Home Assistant OS inside VM.

**Comment by hacker-cb** [comment]
Thank you for the report. Fixed in `master` branch.
Please keep in mind that `main` was renamed to `master`.
